version: "3.3"

services:
  postSQL:
    image: postgres
    restart: always
    environment:
      POSTGRESS_PASSWORD: "123"
      POSTGRES_USER: "root"
      POSTGRES_DB: "go_chat"
    ports:
      - "5432:5432"
    container_name: "sql-postgres"